
  const agentData = {
    name: "",
    player: "",
    attributes: { str: 0, dex: 0, int: 0, con: 0, pre: 0 },
    backgroundName: "",
    className: "",
    nex: "",
    movement: 9,
    maxPv: 0,
    currentPv: 0,
    maxPe: 0,
    currentPe: 0,
    maxSan: 0,
    currentSan: 0,
    maxPd: 0,
    currentPd: 0,
    nexString: "0%",
    isSobrevivendoAoHorror: !1,
    protectionDefense: 0,
    bonusDefense: 0,
    currentProtection: "",
    resistances: "",
    proficiencies: "",
    skills: {},
    attacks: [],
    powers: [],
    rituals: [],
    ritualsDc: 0,
    patent: "",
    prestigePoints: 0,
    inventory: [],
    itemsLimit: { I: 0, II: 0, III: 0, IV: 0 },
    currentItemsLimit: { I: 0, II: 0, III: 0, IV: 0 },
    creditsLimit: "",
    maxLoad: 0,
    currentLoad: 0,
    description: {
      anotation: "",
      physical: "",
      personal: "",
      history: "",
      goal: "",
    },
    deathMarks: [],
    madnessMarks: [],
    deathMode: !1,
    madnessMode: !1,
    sheetPictureURL: "",
    sheetPictureFullPath: "",
    statsClass: "Combatant",
    canDMEdit: !0,
    canAnyoneEdit: !1,
    block: null,
    evade: null,
    private: !1,
    campaignDocId: "",
    resistencias: {},
    imunidades: [],
    vulnerabilidades: [],
    pdMarks: [],
    pdMode: !1,
    isNexLevelOn: !1,
    isPdOn: !1,
  }