services:
  postgres:
    image: postgres:17.5
    container_name: rpg-site-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-db-volume:
